### ISSUE TITLE
image tensor order in PyTorch - video 61:

### ISSUE THREAD

**Issue by ashwinshetgaonkar** [mrdbourke/pytorch-deep-learning#104]
The correct order for image tensor is : `[batch_size,color channels,height,weight]`

**Comment by mrdbourke** [comment]
Hi @ashwinshetgaonkar,

Thank you for the heads up!

But image tensors can come in either order:
* "Channels first" = `[batch_size, color_channels, height, width]` or `[N, C, H, W]`
* "Channels last" = `[batch_size, height, width, color_channels]` or `[N, H, W, C]`

Some frameworks default to using either one.

PyTorch typically starts with using "Channels first" but is capable of handling "Channels last".

Matplotlib on the other hand accepts "Channels last" by default.

See more here: https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html
