### ISSUE TITLE
Notebook 03: timings of the models are compared incorrectly

### ISSUE THREAD

**Issue by pstryczke** [mrdbourke/pytorch-deep-learning#142]
> <html>
> <body>
> <div class="jp-Cell jp-CodeCell jp-Notebook-cell   " style="box-sizing: inherit; padding: var(--jp-cell-padding); margin: 0px; border: none; outline: none; background: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif; font-size: 19.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="jp-Cell jp-CodeCell jp-Notebook-cell   " style="box-sizing: inherit; padding: var(--jp-cell-padding); margin: 0px; border: none; outline: none; background: rgba(0, 0, 0, 0);"><div class="jp-Cell-outputWrapper" style="box-sizing: inherit; display: flex; flex-direction: row; padding: 0px; margin: 5px 0px 0px; overflow: visible;"><div class="jp-OutputArea jp-Cell-outputArea" style="box-sizing: inherit; overflow-y: auto; flex: 1 1 auto;"><div class="jp-OutputArea-child" style="box-sizing: inherit; display: flex; flex-direction: row;"><div class="jp-RenderedHTMLCommon jp-RenderedHTML jp-OutputArea-output jp-OutputArea-executeResult" data-mime-type="text/html" style="box-sizing: inherit; height: auto; overflow: auto; user-select: text; width: 728.438px; flex: 1 1 auto; margin-left: 0px;"><div style="box-sizing: inherit;"><br class="Apple-interchange-newline">
> 
>   | model_name | model_loss | model_acc | training_time
> -- | -- | -- | -- | --
> 1 | FashionMNISTModelV0 | 0.476639 | 83.426518 | 14.974887
> 2 | FashionMNISTModelV1 | 0.685001 | 75.019968 | 16.942553
> 3 | FashionMNISTModelV2 | 0.326644 | 88.228834 | 21.098929
> 
> </div></div></div></div></div></div></div><div class="jp-Cell jp-MarkdownCell jp-Notebook-cell" style="box-sizing: inherit; padding: var(--jp-cell-padding); margin: 0px; border: none; outline: none; background: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.87); font-family: Roboto, -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif; font-size: 19.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="jp-Cell-inputWrapper" style="box-sizing: inherit; display: flex; flex-direction: row; padding: 0px; margin: 0px; overflow: visible;"><div class="jp-Collapser jp-InputCollapser jp-Cell-inputCollapser" style="box-sizing: inherit; flex: 0 0 var(--jp-cell-collapser-width); padding: 0px; margin: 0px; border: none; outline: none; background: rgba(0, 0, 0, 0); border-radius: var(--jp-border-radius); opacity: 1;"></div><div class="jp-InputArea jp-Cell-inputArea" style="box-sizing: inherit; display: flex; flex-direction: row; flex: 1 1 auto; width: 807.625px;"><div class="jp-RenderedHTMLCommon jp-RenderedMarkdown jp-MarkdownOutput " data-mime-type="text/markdown" style="box-sizing: inherit; flex: 1 1 auto; margin-top: 0px; margin-bottom: 0px; padding: 0px; width: 807.625px; overflow: auto;"><p style="box-sizing: inherit;">It looks like our CNN (<code style="box-sizing: inherit; font-feature-settings: &quot;kern&quot;; font-family: var(--md-code-font-family); color: var(--md-code-fg-color); direction: ltr; background-color: var(--md-code-bg-color); border-radius: 0.1rem; -webkit-box-decoration-break: clone; font-size: 0.85em; padding: 0px 0.294118em; word-break: break-word; -webkit-tap-highlight-color: transparent; outline: none;">FashionMNISTModelV2</code>) model performed the best (lowest loss, highest accuracy) but had the longest training time.</p><p style="box-sizing: inherit;">And our baseline model (<code style="box-sizing: inherit; font-feature-settings: &quot;kern&quot;; font-family: var(--md-code-font-family); color: var(--md-code-fg-color); direction: ltr; background-color: var(--md-code-bg-color); border-radius: 0.1rem; -webkit-box-decoration-break: clone; font-size: 0.85em; padding: 0px 0.294118em; word-break: break-word; -webkit-tap-highlight-color: transparent; outline: none;">FashionMNISTModelV0</code>) performed better than<span> </span><code style="box-sizing: inherit; font-feature-settings: &quot;kern&quot;; font-family: var(--md-code-font-family); color: var(--md-code-fg-color); direction: ltr; background-color: var(--md-code-bg-color); border-radius: 0.1rem; -webkit-box-decoration-break: clone; font-size: 0.85em; padding: 0px 0.294118em; word-break: break-word; -webkit-tap-highlight-color: transparent; outline: none;">model_1</code><span> </span>(<code style="box-sizing: inherit; font-feature-settings: &quot;kern&quot;; font-family: var(--md-code-font-family); color: var(--md-code-fg-color); direction: ltr; background-color: var(--md-code-bg-color); border-radius: 0.1rem; -webkit-box-decoration-break: clone; font-size: 0.85em; padding: 0px 0.294118em; word-break: break-word; -webkit-tap-highlight-color: transparent; outline: none;">FashionMNISTModelV1</code>) but took longer to train (this is likely because we used a CPU to train<span> </span><code style="box-sizing: inherit; font-feature-settings: &quot;kern&quot;; font-family: var(--md-code-font-family); color: var(--md-code-fg-color); direction: ltr; background-color: var(--md-code-bg-color); border-radius: 0.1rem; -webkit-box-decoration-break: clone; font-size: 0.85em; padding: 0px 0.294118em; word-break: break-word; -webkit-tap-highlight-color: transparent; outline: none;">model_0</code><span> </span>but a GPU to train<span> </span><code style="box-sizing: inherit; font-feature-settings: &quot;kern&quot;; font-family: var(--md-code-font-family); color: var(--md-code-fg-color); direction: ltr; background-color: var(--md-code-bg-color); border-radius: 0.1rem; -webkit-box-decoration-break: clone; font-size: 0.85em; padding: 0px 0.294118em; word-break: break-word; -webkit-tap-highlight-color: transparent; outline: none;">model_1</code>).</p></div></div></div></div>
> </body>
> </html>

Training time of `FashionMNISTModelV0` is lower (14.97s) than `FashionMNISTModelV1` (16.94s). but the description says the opposite.

**Comment by mrdbourke** [comment]
Thank you!

You're right, this could be more clear.

The training time column really depends on the hardware you're running on (the documentation notebooks are built on my local machine but the videos are done on Google Colab).

Made the description clearer in https://github.com/mrdbourke/pytorch-deep-learning/commit/a007626bfc29702dccdfad03a75ed325541b3cc3
