### ISSUE TITLE
Typo in the site

### ISSUE THREAD

**Issue by diegorodriguezv** [mrdbourke/pytorch-deep-learning#155]
At: https://www.learnpytorch.io/00_pytorch_fundamentals/
PyTorch is also used in other industries such as argiculture to...
should be:
PyTorch is also used in other industries such as agriculture to...
Please correct me if this typo should be reported elsewhere.
Thanks for the course.

**Comment by mrdbourke** [comment]
Thank you for this!

Fixed here: https://github.com/mrdbourke/pytorch-deep-learning/commit/42717cd5eccb50c5c04535a486e55659d65f986b
