### ISSUE TITLE
PyTorch syntax error (torch undefined)

### ISSUE THREAD

**Issue by potaytoo** [mrdbourke/pytorch-deep-learning#175]
After writing the following code:-

```
## Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 10, 10)
random_tensor

The response I get is this:-

_**NameError Traceback (most recent call last)

in
1 ## Create a random tensor of size (3, 4)
----> 2 random_tensor = torch.rand(1, 10, 10)
3 random_tensor_

NameError: name 'torch' is not defined**_
```

Please help me on how to solve this issue

**Comment by mrdbourke** [comment]
Hi @potaytoo,

Have you tried to run `import torch`? 

Without `import torch`, you will get issues like the one you're facing.

If you're using Google Colab, you should just be able to run a single cell with `import torch` (I usually do this at the start of each notebook).

**Note:** If you're starting a new session in a notebook, you will have to run the `import torch` cell again to get it back.

**Comment by potaytoo** [comment]
> Hi @potaytoo,
> 
> Have you tried to run `import torch`?
> 
> Without `import torch`, you will get issues like the one you're facing.
> 
> If you're using Google Colab, you should just be able to run a single cell with `import torch` (I usually do this at the start of each notebook).
> 
> **Note:** If you're starting a new session in a notebook, you will have to run the `import torch` cell again to get it back.

 Thank you, I had not done that after I had reconnected. :)
