### ISSUE TITLE
00_pytorch_fundamentals_exercises Qn 9

### ISSUE THREAD

**Issue by chewyh26** [mrdbourke/pytorch-deep-learning#182]
I wrote a random example to summarise and clarify my last reply
<img width="392" alt="code" src="https://user-images.githubusercontent.com/66502176/202431084-93e7a6de-757d-4f52-ae2c-008d5f4c3d33.png">

_Originally posted by @chewyh26 in https://github.com/mrdbourke/pytorch-deep-learning/discussions/181#discussioncomment-4166390_
    
My question remained unresolved

**Comment by mrdbourke** [comment]
Hi @chewyh26,

Fantastic question.

See this discussion answer for more details - https://github.com/mrdbourke/pytorch-deep-learning/discussions/181#discussioncomment-4174347
