### ISSUE TITLE
difficult

### ISSUE THREAD

**Issue by Aalok45** [mrdbourke/pytorch-deep-learning#206]
https://colab.research.google.com/drive/1typUHVUR43UITvrlH4vEg0UZYgeOcrVe#scrollTo=FBKc0qrMHk7f&uniqifier=1

**Comment by mrdbourke** [comment]
Hi @Aalok45,

I'm not sure what's happening here, could you please add more details?

I'll close this issue in a week or so if I don't hear back from you.

Best,

Daniel

**Comment by mrdbourke** [comment]
Closing this due to no added details.
