### ISSUE TITLE
One of the notebooks is invalid

### ISSUE THREAD

**Issue by Cheerstoast** [mrdbourke/pytorch-deep-learning#230]
Path: pytorch-deep-learning/extras/solutions/03_pytorch_computer_vision_exercise_solutions.ipynb

Invalid Notebook
The Notebook Does Not Appear to Be Valid JSON

This is the only invalid notebook in this repository.

**Comment by aronvandepol** [comment]
Properly opens for me in both VSCode locally, and imported into Google Collab. Did you save it the correct manner?

**Comment by Cheerstoast** [comment]
Umm, the JSON is invalid, so it cannot be opened anywhere.
See https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/03_pytorch_computer_vision_exercise_solutions.ipynb

As compared to https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/04_pytorch_custom_datasets_exercise_solutions.ipynb,
which is valid.

**Comment by Cheerstoast** [comment]
Okay. I'll close issue now. Un-corrupt it soon!
