### ISSUE TITLE
A little change in the cheatsheet you provided.

### ISSUE THREAD

**Issue by Cheerstoast** [mrdbourke/pytorch-deep-learning#239]
Your cheatsheet's webpage: https://www.learnpytorch.io/pytorch_cheatsheet/
Your cheatsheet's path: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/pytorch_cheatsheet.ipynb

### In codeblock 11 (In [11]):

    # Setup device-agnostic code 
    if torch.cuda.is_available():
        device = "cuda" # NVIDIA GPU
    elif torch.backends.mps_is_available():
        device = "mps" # Apple GPU
    else:
        device = "cpu"
    
    print(f"Using device: {device}")

### Here's what ChatGPT has to say about this:
It looks like you are trying to use the mps_is_available attribute of the torch.backends module, but it is giving you an error saying that the attribute does not exist.

This attribute was used in older versions of PyTorch to check whether the Metal Performance Shaders (MPS) framework was available on the system. However, this attribute has been removed in newer versions of PyTorch.

Instead of using torch.backends.mps_is_available(), you can use torch.backends.mps.is_available()

**Comment by shmuhammad2004** [comment]
Yes, I confirm it gives an error too.

**Comment by mrdbourke** [comment]
Thank you for this!

I didn't know that! Looks like ChatGPT is an epic troubleshooter.

I will fix it this coming week!
