### ISSUE TITLE
How to make illustration as you did?

### ISSUE THREAD

**Issue by suredream** [mrdbourke/pytorch-deep-learning#241]
Hi Daniel:

What tool you used to create annotated code as below? Thanks,

![image](https://user-images.githubusercontent.com/1661077/210159182-b5535454-9d65-452b-823b-7453a03235a7.png)

**Comment by mrdbourke** [comment]
Hi there @suredream!

I used Keynote for Mac to make all of the slides - https://www.apple.com/au/keynote/ 

<img width="2032" alt="Screen Shot 2023-01-12 at 11 09 45 am" src="https://user-images.githubusercontent.com/16750345/211951872-04ce4263-3668-4cbf-992f-ea979fda3d71.png">

**Comment by suredream** [comment]
Gosh, I should think of. Tks!
