### ISSUE TITLE
03_pytorch_computer_vision_exercise_solutions.ipynb

### ISSUE THREAD

**Issue by catechumen27** [mrdbourke/pytorch-deep-learning#243]
"Invalid Notebook
The Notebook Does Not Appear to Be Valid JSON"

**Comment by mrdbourke** [comment]
Thank you for this!

Fixed with https://github.com/mrdbourke/pytorch-deep-learning/pull/240 

See the fixed link here: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/03_pytorch_computer_vision_exercise_solutions.ipynb

**Comment by NEELANATARAJAN** [comment]
This is still an invalid notebook
