### ISSUE TITLE
Sigmoid and ReLU plots

### ISSUE THREAD

**Issue by iamyifan** [mrdbourke/pytorch-deep-learning#266]
Hi, thank you so much for this tutorial ; )

Just a small concern, on the [page](https://www.learnpytorch.io/02_pytorch_classification/#4-make-predictions-and-evaluate-the-model), the Sigmoid and RuLU plots in section `7. Replicating non-linear activation functions` seems to have the wrong x-axis, should it be `range(-10, 10)`?

**Comment by mrdbourke** [comment]
Hi @iamyifan,

Great pickup!

However the x-axis is reflecting the "number of elements" in the following:

```python
# Create a toy tensor (similar to the data going into our model(s))
A = torch.arange(-10, 10, 1, dtype=torch.float32)
A
```

```python
>>> tensor([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,   1.,
          2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
```

There are 20 elements, hence the axis goes from 0-20.

```python
len(A)
```

```python
>>> 20
```
