### ISSUE TITLE
mlp_dropout is not int

### ISSUE THREAD

**Issue by GabrielTellez** [mrdbourke/pytorch-deep-learning#270]
In notebook https://github.com/mrdbourke/pytorch-deep-learning/blob/main/08_pytorch_paper_replicating.ipynb
mpl_dropout is hinted as int but its default value is 0.1 which is not an integer.

**Comment by mrdbourke** [comment]
Thank you for this! 

Just fixed this here: https://github.com/mrdbourke/pytorch-deep-learning/pull/263
