### ISSUE TITLE
Typo in the section "03. PyTorch Computer Vision"

### ISSUE THREAD

**Issue by vanilladucky** [mrdbourke/pytorch-deep-learning#332]
<img width="647" alt="Screenshot 2023-03-07 at 4 58 31 PM" src="https://user-images.githubusercontent.com/77542415/223359948-94551eae-1d4e-42d1-ae87-699b9f838b26.png">

I was going through the third section and came across the 'conovlutional' typo.

**Comment by mrdbourke** [comment]
Hey hey!

Thank you for this! 

Fixed here: https://github.com/mrdbourke/pytorch-deep-learning/commit/29595a60dcf43af2ca21b0a2241fe74551db3e6a
