### ISSUE TITLE
Could add more detail to the usage of torchmetrics.Accuracy()

### ISSUE THREAD

**Issue by vanilladucky** [mrdbourke/pytorch-deep-learning#333]
`# Note: could also use torchmetrics.Accuracy()`
[From "03.PyTorch Computer Vision", section 3.1]

When mentioning the alternate usage of torchmetrics.Accuracy(), I think it can be updated to 

`torchmetrics.Accuracy(task = 'multiclass', num_classes=len(class_names)).to(device)`

Merely installing torchmetrics and using torchmetrics.Accuracy() apparently doesn't do the trick.

**Comment by mrdbourke** [comment]
Hi @vanilladucky,

Thank you for the heads up! 

I'd love to make this change.

Could you be more specific?

As in, what code would you change/what would you change it to?

You could potentially make a pull request if you'd like to implement the change yourself.

- Daniel

**Comment by mrdbourke** [comment]
Merged and fixed! 

Thank you :)
