### ISSUE TITLE
Find someone to go through the course materials, proof read and execute code to see if it all works

### ISSUE THREAD

**Issue by mrdbourke** [mrdbourke/pytorch-deep-learning#35]

**Comment by beneyal** [comment]
Hello Daniel 👋 

If this issue is still relevant, I'll gladly help!

**Comment by mrdbourke** [comment]
Hi Ben!

This is definitely still relevant.

I'm working through finishing off the first 3 modules (00, 01, 02) now.

Notebook 00 just finished: 
* Book version - https://www.learnpytorch.io/00_pytorch_fundamentals/
* GitHub version - https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

Feel free to read through 00, 01, 02 and submit any pull requests for fixes.

I'd love to hear if there's anything you think can be improved.

**Comment by mrdbourke** [comment]
I'll be working through the rest of the notebooks over the next couple of months to get them publishable (to the book version + the course videos too).

**Comment by loevlie** [comment]
Hey Daniel!  

I am a fan of your content as well as PyTorch.  I can definitely help with proofreading. My computer is a Mac M1 so I can also help by testing code on CPU.

**Comment by mrdbourke** [comment]
Hey @loevlie,

I'd love that, but I'd recommend running the materials in Google Colab (where the course is taught), that way you'll get access to a GPU as well.

If you end up running locally as well, feel free to make a pull request for errors you find.

**Comment by Aryan-Garg** [comment]
Hey, I'm super late to the party but if I can be of any help, let me know @mrdbourke! 
Anyways thanks for the awesome e-book and the content 🤘

**Comment by mrdbourke** [comment]
@Aryan-Garg yo! not too late at all!

I'm going to close this specific issue but feel free to go through any of the materials and run them and if you find any errors, you can post an issue/make a pull request.

I welcome all feedback/improvements :)
