### ISSUE TITLE
Table of Contents not working in the book version

### ISSUE THREAD

**Issue by manojent** [mrdbourke/pytorch-deep-learning#362]
Hello Daniel,

There seems to be problem with the book version of the course (learnpytorch.io) or at least I am facing it.

For most of the sections, I am unable to navigate to a particular sub-section of a chapter using the table of contents on the right side. This making it very difficult for me to jump to the specific sub-section that I am following on Udemy. 

Is it just me making some mistake or is there a specific issue? 

Any help/resolution would be highly appreciated.

Thanking in anticipation.

Manoj

**Comment by mrdbourke** [comment]
Hi @manojent,

Thank you for letting me know.

I didn't know this was an issue and I'm not currently sure what's causing it.

Let me try and figure it out and come back to you!

**Comment by mrdbourke** [comment]
Hi @manojent,

It seems to be fixed for me - does it work for you?

**Comment by manojent** [comment]
Hey @mrdbourke 

Yes, it works fine. Appreciate the prompt action and reply.

And once again, thank you for creating such a marvelous course😊.

God bless and cheer!!!!
