### ISSUE TITLE
Add Reinforcement learning as Extra resource

### ISSUE THREAD

**Issue by MezoPeeta** [mrdbourke/pytorch-deep-learning#429]
Hey Daniel ^^ , mind if u add reinforcement learning and how to start with it in learnpytorch.io extra resources , since it's so fun and I like it since it's more fun than others supervised and unsupervised  for me . thanks ^^

**Comment by mrdbourke** [comment]
Hey @MezoPeeta , 

Great suggestion!

For now, my own reinforcement learning skills aren't quite good enough to create a course section from.

But if I do end up learning more on the topic, I'll definitely consider adding it to learnpytorch.io!
