### ISSUE TITLE
Missing course number 5 in colab format

### ISSUE THREAD

**Issue by velociraptux** [mrdbourke/pytorch-deep-learning#430]
I cant open the course 5 by clicking on ''open with colab'' like all other course
Page in .md format. Other in .ipynb
https://github.com/mrdbourke/pytorch-deep-learning/blob/main/05_pytorch_going_modular.md

**Comment by ceferisbarov** [comment]
This is a markdown file. Unlike Jupyter Notebooks, they do not contain code cells that you can run. Since there is no code to run in this file, there is also no need to use Google Colab. You can test the code samples given in this lesson in a separate environment, if you like.

**Comment by mrdbourke** [comment]
Hi @velociraptux,

@ceferisbarov is right.

The notebook 05 (https://www.learnpytorch.io/05_pytorch_going_modular/) is a markdown section (`.md`) rather than a Jupyter Notebook.

This is because the section is mostly for reference/learning rather than explicitly running code.
