### ISSUE TITLE
`helper_functions.py` already exists - PyTorch_Neural_Network_Classification_section

### ISSUE THREAD

**Issue by mfarhadirad** [mrdbourke/pytorch-deep-learning#559]
"Hi, thank you so much for your perfect course.

I encountered an error when trying to use helper_function.py. The specific error message I received was 'name 'false' is not defined'.

When I click on the helper_functions.py file from the left side of the Colab interface, it doesn't display anything. I've also downloaded the file, but it still doesn't display any content in my VSCode editor. The only place I can view the code is in the GitHub repository you provided."

**Comment by dikasterion** [comment]
I got the same problem here

**Comment by dikasterion** [comment]
just found out the culprit.
wrong file (helper_functions.py)has downloaded (check the url)
so I deleted the wrong file and replaced with right one, there's no error message anymore.

**Comment by mrdbourke** [comment]
Hi @mfarhadirad , 

Did you manage to fix the issue?

@dikasterion good find!

---

If you're still having issues with importing, you can try this snippet of code (to redownload the file if the import fails):

```python
import requests
from pathlib import Path 

# Download helper functions from Learn PyTorch repo (if not already downloaded)
try:
  from helper_functions import plot_predictions, plot_decision_boundary
except:
  print("Cannot import from helper_functions, downloading helper_functions.py")
  request = requests.get("https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/helper_functions.py")
  with open("helper_functions.py", "wb") as f:
    f.write(request.content)

  # Import helper functions after download
  from helper_functions import plot_predictions, plot_decision_boundary
  ```
  
  However, once you have the `helper_functions.py` file (locally), you shouldn't have to redownload it.
  
  If you're using Google Colab, you'll need to redownload it for every new notebook.

**Comment by mfarhadirad** [comment]
Hi @mrdbourke 
Fortunately, yes,
It was my mistake. I had mistakenly used the GitHub URL 'https://github.com/mrdbourke/pytorch-deep-learning/blob/main/helper_functions.py', instead of the correct URL 'https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/helper_functions.py'.

**Comment by mrdbourke** [comment]
Glad you got it fixed!
