### ISSUE TITLE
DataLoader Value

### ISSUE THREAD

**Issue by Diwura** [mrdbourke/pytorch-deep-learning#586]
Thanks for this course, it is really amazing. I might be missing something, however at 19:12:00  in the course video the X variable returns a  value of [16,1,28,28] as opposed to [32,1,28,28] since the test_dataloader has a batch size of 32. I don't seem to understand this.

**Comment by mrdbourke** [comment]
Hi @Diwura , 

Thank you for the kind words!

Yes, that is confusing.

However, it could be because the *last* batch of the `test_dataloader` doesn't have enough samples to be `32`. 

For example, if you have 1000 samples and `batch_size=32`, you will end up with 31 batches of 32 and 1 batch of 8 (because 1000/32 doesn't divide equally, the last batch is of size 8).

Example code: 

```python
import math

num_samples = 1000
batch_size = 32

num_batches_in_num_samples = math.floor(num_samples / batch_size)
num_leftover = num_samples % batch_size
total_samples = (num_batches_in_num_samples * batch_size) + num_leftover

print(f"Batch size of {batch_size} fits into number of samples ({num_samples}): {num_batches_in_num_samples} times with {num_leftover} samples leftover.")
print(f"This means there are {num_batches_in_num_samples} batches of size {batch_size}.")
if num_leftover > 0:
  print(f"And one batch of {num_leftover}.")
print(f"Total samples in batches: {total_samples}")
```

Output: 

```
Batch size of 32 fits into number of samples (1000): 31 times with 8 samples leftover.
This means there are 31 batches of size 32.
And one batch of 8.
Total samples in batches: 1000
```

Example notebook: https://colab.research.google.com/drive/13UgGnjf-dCGHundf9PPzUnYDaMOGQ1Ra?usp=sharing

Let me know if this clears things up!

**Comment by Diwura** [comment]
> Hi @Diwura ,
> 
> Thank you for the kind words!
> 
> Yes, that is confusing.
> 
> However, it could be because the _last_ batch of the `test_dataloader` doesn't have enough samples to be `32`.
> 
> For example, if you have 1000 samples and `batch_size=32`, you will end up with 31 batches of 32 and 1 batch of 8 (because 1000/32 doesn't divide equally, the last batch is of size 8).
> 
> Example code:
> 
> ```python
> import math
> 
> num_samples = 1000
> batch_size = 32
> 
> num_batches_in_num_samples = math.floor(num_samples / batch_size)
> num_leftover = num_samples % batch_size
> total_samples = (num_batches_in_num_samples * batch_size) + num_leftover
> 
> print(f"Batch size of {batch_size} fits into number of samples ({num_samples}): {num_batches_in_num_samples} times with {num_leftover} samples leftover.")
> print(f"This means there are {num_batches_in_num_samples} batches of size {batch_size}.")
> if num_leftover > 0:
>   print(f"And one batch of {num_leftover}.")
> print(f"Total samples in batches: {total_samples}")
> ```
> 
> Output:
> 
> ```
> Batch size of 32 fits into number of samples (1000): 31 times with 8 samples leftover.
> This means there are 31 batches of size 32.
> And one batch of 8.
> Total samples in batches: 1000
> ```
> 
> Example notebook: https://colab.research.google.com/drive/13UgGnjf-dCGHundf9PPzUnYDaMOGQ1Ra?usp=sharing
> 
> Let me know if this clears things up!

Hello @mrdbourke yes it does and thank you for your quick response. I get the idea now but one thing that will finally clarify things for me is. If the last batch is 8 why then do I get a test_data loader of [16,1,28,28] should it not be [8,1,28,28]

Thank you very much.

**Comment by mrdbourke** [comment]
Hi @Diwura ,

The last clarification is that the last batch size you get will depend on the actual size of your data. 

The sample size of 1000 above is only an example.

It will differ in practice depending on how many samples you have/what your batch size is.

To learn more, my recommendation is to experiment with different numbers of samples/batch size.
