### ISSUE TITLE
Typo: Pytorch Experiment Tracking Lesson

### ISSUE THREAD

**Issue by ashjostan7** [mrdbourke/pytorch-deep-learning#595]
Thank you for the great resource! Just highlighting a small typo, that might save some minor confusion for others using it:

Section 8 [View Experiments in TensorBaord] of lesson 7.

Post running the experiments, the image highlights the experiment- `efnetb0, 10 epochs, 20% data` as the experiment with the lowest test accuracy. 
Image - https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/07-tensorboard-lowest-test-loss.png

But in the text following the image, the lesson mentions that the experiment - `effnetb2, 10 epochs, 20% data` has the lowest test accuracy.

![Capture](https://github.com/mrdbourke/pytorch-deep-learning/assets/22536011/7fc4f155-ec2d-4fee-8f77-bbd79967ff09)

**Comment by mrdbourke** [comment]
Thank you for this!

Fixed: https://www.learnpytorch.io/07_pytorch_experiment_tracking/
<img width="812" alt="Screenshot 2023-10-12 at 2 13 56 pm" src="https://github.com/mrdbourke/pytorch-deep-learning/assets/16750345/60b563a5-f265-4f40-b9bc-673a27924484">
