### ISSUE TITLE
Typo: Transfer Learning 6.4

### ISSUE THREAD

**Issue by nprisbrey** [mrdbourke/pytorch-deep-learning#604]
The first sentence of the Transfer Learning page, section Train Model (4) uses the word "pretraiend" instead of "pretrained".

https://www.learnpytorch.io/06_pytorch_transfer_learning/#4-train-model

**Comment by nprisbrey** [comment]
Another typo: "...one go, a fair bit to keep track of, let's [**missing verb**] what their results look like..." in the "What we're going to cover" section of the PyTorch Experiment Tracking page. There's a missing verb after the word "let's".

https://www.learnpytorch.io/07_pytorch_experiment_tracking/#what-were-going-to-cover

**Comment by nprisbrey** [comment]
Another typo: "We're going to focused on write PyTorch code to create these layers, ..." should be something like "We're going to **be** focused on **writing** PyTorch code to create these layers, ...". From the "08. PyTorch Paper Replicating" page in section "3.2.1 Exploring Figure 1".

https://www.learnpytorch.io/08_pytorch_paper_replicating/#321-exploring-figure-1

**Comment by nprisbrey** [comment]
Another typo: "...replicating the simplest version fo the model possible." should contain "of" instead of "fo". Found in the "08. PyTorch Paper Replicating" page in section "3.3 My workflow for replicating papers".

https://www.learnpytorch.io/08_pytorch_paper_replicating/#33-my-workflow-for-replicating-papers

**Comment by nprisbrey** [comment]
Another typo: "Desried output (flattened 2D patches): ..." should be "desired" instead of "desried". Found in the "08. PyTorch Paper Replicating" page in section "4.4 Flattening the patch embedding with torch.nn.Flatten()".

https://www.learnpytorch.io/08_pytorch_paper_replicating/#44-flattening-the-patch-embedding-with-torchnnflatten

**Comment by nprisbrey** [comment]
Another typo: "...in practice, you'd like create it..." should be "you'd likely create it". Found in the "08. PyTorch Paper Replicating" page in section "4.6 Creating the class token embedding".

https://www.learnpytorch.io/08_pytorch_paper_replicating/#46-creating-the-class-token-embedding

**Comment by mrdbourke** [comment]
Just fixed all of these! Thank you thank you!

**Comment by mrdbourke** [comment]
Let me know if you have more in another issue :)

**Comment by bathicodes** [comment]
Tried to download weights from the pre-trained `EfficientNet_B0` model by using the below code block.

```
# OLD: Setup the model with pretrained weights and send it to the target device (this was prior to torchvision v0.13)
# model = torchvision.models.efficientnet_b0(pretrained=True).to(device) # OLD method (with pretrained=True)

# NEW: Setup the model with pretrained weights and send it to the target device (torchvision v0.13+)
weights = torchvision.models.EfficientNet_B0_Weights.DEFAULT # .DEFAULT = best available weights 
model = torchvision.models.efficientnet_b0(weights=weights).to(device)

model # uncomment to output (it's very long)
```

However this error keep showing.
invalid hash value (expected "3dd342df", got "7f5810bc96def8f7552d5b7e68d53c4786f81167d28291b21c0d90e1fca14934")
