### ISSUE TITLE
RuntimeError: a Tensor with 800 elements cannot be converted to Scalar

### ISSUE THREAD

**Issue by raagul1234** [mrdbourke/pytorch-deep-learning#626]
a error came at the end of program regarding tensor conversion can anyone please help me wid this one

https://github.com/raagul1234/summa/blob/02f6240617bc1df0c30316d297519228a171f40a/untitled1.py

**Comment by mrdbourke** [comment]
Hi @raagul1234 , 

Your `accuracy_fn` requires the `.sum()` method, see: 

```python
def accuracy_fn(y_true,y_preds):
  correct = torch.eq(y_true, y_preds).sum().item()
  acc = (correct/len(y_preds)) * 100
  return acc
```

Also, be sure to call `loss_fn()` to calculate the loss:

```python
# Train
loss = loss_fn(y_logits, y_train)

# Test
test_loss = loss_fn(test_logits, y_test)
```

Also, make sure your `test_pred` are calculated on your `test_logits`:

```python
with torch.inference_mode():
     test_logits = model_0(X_test).squeeze()
     test_pred = torch.round(torch.sigmoid(test_logits)) # these should be test_logits (not y_logits)
```

See the fixed Colab notebook here: https://colab.research.google.com/drive/1chus3VDPLkDAqam4On0I_3kx3w2o-EvM?usp=sharing

**Comment by raagul1234** [comment]
hiiii @mrdbourke  Thanks  a lot brother 
problem resolved!!!!

**Comment by mrdbourke** [comment]
Glad to hear! You're welcome!

PS I'm gonna close this issue now :)
