### ISSUE TITLE
Fixing numbering of excercises on the 00 notebook

### ISSUE THREAD

**Issue by shivan-s** [mrdbourke/pytorch-deep-learning#82]
The number is not correct for the exercises for the 00th notebook.

I'll provide a pull request ;)

**Comment by shivan-s** [comment]
The source code is correct, but the way it renders makes it look wrong. Really strange!

**Comment by mrdbourke** [comment]
Thank you for this :) 

Seems converting `.ipynb`'s to markdown can mess up dot points sometimes.

I fixed it here though: https://www.learnpytorch.io/01_pytorch_workflow/#exercises
