### ISSUE TITLE
Pytorch Fundamental Exercise Problems

### ISSUE THREAD

**Issue by dsnal** [mrdbourke/pytorch-deep-learning#84]
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In the last part of the exercise questions(1-4) , there is a question which refers to the above one Number (4). But the question said 
" Perform a matrix multiplication on the tensors you created in 6 ".  
Also the next one 
"Find the maximum and minimum values of the output of 7 "
I know they mean above questions.But there is no Number 6 or 7 in exercise.  Wrong numbering I guess. 

In the first part of the question, Question Number 4 
" Set the random seed to 0 and do 2 & 3 over again "
It sounded like I have to set random seed 0 for both  2 and 3. It only needed for Q.2 . Not that big of a deal. But for me it is kinda misleading.

Loving this course, so far

**Comment by mrdbourke** [comment]
Thank you for the kind words!

And thank you for letting me know of the formatting issue, looks like the code blocks were interrupting the dot point ordering.

Fixed it now though: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
