### ISSUE TITLE
06 Error with pretrained Model

### ISSUE THREAD

**Issue by UzumymW839** [mrdbourke/pytorch-deep-learning#905]
When I try to train the pre-trained model in chapter "06 transfer learning", I get the following error:

 raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

I copied everything right, I guess. Does anyone know where my mistake lies?

**Comment by tberends** [comment]
In chapter 05 I ran into the same issue. By setting the number of workers in the DataLoader to 0, it solved this issue for me.
