### ISSUE TITLE
Regarding course availability on udemy

### ISSUE THREAD

**Issue by akashsonowal** [mrdbourke/pytorch-deep-learning#91]
Hey Daniel! When will this course be listed on udemy?

**Comment by mrdbourke** [comment]
Hey @akashsonowal!

No dates for Udemy release yet.

Likely at the end of completion of section 09 (the last section).

Stay tuned for updates via the log: https://github.com/mrdbourke/pytorch-deep-learning#log

Or the projects page: https://github.com/users/mrdbourke/projects/1/views/4
