### ISSUE TITLE
Part4_ make predictions and get model 0 results

### ISSUE THREAD

**Issue by ulfat191** [mrdbourke/pytorch-deep-learning#93]
I am getting very less accuracy score when I wrote the function for model evaluation. All other parts of the code are fine and even the accuracy metrics while I run the epochs in part 3 are also close to your ones. 

I went through the code several times but I could not figure out the issue. 

You can access my notebook from [this link](https://colab.research.google.com/drive/1O4l3h0EIx1VPuCbvEhCkuZhoUDidjkiu?usp=sharing). 

Can you please guide me through what is wrong ?

**Comment by mrdbourke** [comment]
Hi @ulfat191,

Did you manage to solve your problem?

Did your code work with the code from the sample notebook?

Looking at your notebook it looks like your model is making good predictions, can you perhaps be more specific with the code you're running and the problems you're having?

**Comment by ulfat191** [comment]
Yeah, I solved it a long time back.

Thanks for reaching out.
