### ISSUE TITLE
09. PyTorch Model Deployment - **9.3 Uploading to Hugging Face**, RuntimeError: Could not infer dtype of numpy.uint8

### ISSUE THREAD

**Issue by huangBnn** [mrdbourke/pytorch-deep-learning#981]
### **Runtime error**
line 365, in _start_caching
    client_utils.synchronize_async(self.cache)
  File "/usr/local/lib/python3.10/site-packages/gradio_client/utils.py", line 855, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 487, in cache
    prediction = await Context.root_block.process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 832, in wrapper
    response = f(*args, **kwargs)

  **File "/home/user/app/app.py", line 38, in predict**
    img = effnetb2_transforms(img).unsqueeze(0)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torchvision/transforms/_presets.py", line 59, in forward
    img = F.pil_to_tensor(img)
  File "/usr/local/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 205, in pil_to_tensor
    img = torch.as_tensor(np.array(pic, copy=True))
**RuntimeError: Could not infer dtype of numpy.uint8**

but I successfully replicate **8.7 Turning our FoodVision Mini Gradio app into a Python script (app.py)**

### **Dependencies:**
Warning!!! Possibly conflicting dependencies found:
* selenium==4.3.0
 - urllib3 [required: ~=1.26, installed: 2.2.2]
------------------------------------------------------------------------
analytics-python==1.4.post1
├── backoff [required: ==1.10.0, installed: 1.10.0]
├── monotonic [required: >=1.5, installed: 1.6]
├── python-dateutil [required: >2.1, installed: 2.9.0.post0]
│   └── six [required: >=1.5, installed: 1.16.0]
├── requests [required: >=2.7,<3.0, installed: 2.32.3]
│   ├── certifi [required: >=2017.4.17, installed: 2022.6.15]
│   ├── charset-normalizer [required: >=2,<4, installed: 2.1.0]
│   ├── idna [required: >=2.5,<4, installed: 3.3]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.2]
└── six [required: >=1.5, installed: 1.16.0]
beautifulsoup4==4.12.3
└── soupsieve [required: >1.2, installed: 2.5]
Flask-CacheBuster==1.0.0
└── Flask [required: Any, installed: 3.0.3]
    ├── blinker [required: >=1.6.2, installed: 1.8.2]
    ├── click [required: >=8.1.3, installed: 8.1.7]
    │   └── colorama [required: Any, installed: 0.4.6]
    ├── itsdangerous [required: >=2.1.2, installed: 2.2.0]
    ├── Jinja2 [required: >=3.1.2, installed: 3.1.3]
    │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
    └── Werkzeug [required: >=3.0.0, installed: 3.0.3]
        └── MarkupSafe [required: >=2.1.1, installed: 2.1.5]
Flask-Cors==4.0.1
└── Flask [required: >=0.9, installed: 3.0.3]
    ├── blinker [required: >=1.6.2, installed: 1.8.2]
    ├── click [required: >=8.1.3, installed: 8.1.7]
    │   └── colorama [required: Any, installed: 0.4.6]
    ├── itsdangerous [required: >=2.1.2, installed: 2.2.0]
    ├── Jinja2 [required: >=3.1.2, installed: 3.1.3]
    │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
    └── Werkzeug [required: >=3.0.0, installed: 3.0.3]
        └── MarkupSafe [required: >=2.1.1, installed: 2.1.5]
Flask-Login==0.6.3
├── Flask [required: >=1.0.4, installed: 3.0.3]
│   ├── blinker [required: >=1.6.2, installed: 1.8.2]
│   ├── click [required: >=8.1.3, installed: 8.1.7]
│   │   └── colorama [required: Any, installed: 0.4.6]
│   ├── itsdangerous [required: >=2.1.2, installed: 2.2.0]
│   ├── Jinja2 [required: >=3.1.2, installed: 3.1.3]
│   │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
│   └── Werkzeug [required: >=3.0.0, installed: 3.0.3]
│       └── MarkupSafe [required: >=2.1.1, installed: 2.1.5]
└── Werkzeug [required: >=1.0.1, installed: 3.0.3]
    └── MarkupSafe [required: >=2.1.1, installed: 2.1.5]
gradio==4.36.1
├── aiofiles [required: >=22.0,<24.0, installed: 23.2.1]
├── altair [required: >=4.2.0,<6.0, installed: 5.3.0]
│   ├── Jinja2 [required: Any, installed: 3.1.3]
│   │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
│   ├── jsonschema [required: >=3.0, installed: 4.22.0]
│   │   ├── attrs [required: >=22.2.0, installed: 23.2.0]
│   │   ├── jsonschema-specifications [required: >=2023.03.6, installed: 2023.12.1]
│   │   │   └── referencing [required: >=0.31.0, installed: 0.35.1]
│   │   │       ├── attrs [required: >=22.2.0, installed: 23.2.0]
│   │   │       └── rpds-py [required: >=0.7.0, installed: 0.18.1]
│   │   ├── referencing [required: >=0.28.4, installed: 0.35.1]
│   │   │   ├── attrs [required: >=22.2.0, installed: 23.2.0]
│   │   │   └── rpds-py [required: >=0.7.0, installed: 0.18.1]
│   │   └── rpds-py [required: >=0.7.1, installed: 0.18.1]
│   ├── numpy [required: Any, installed: 1.24.4]
│   ├── packaging [required: Any, installed: 24.0]
│   ├── pandas [required: >=0.25, installed: 2.2.2]
│   │   ├── numpy [required: >=1.22.4, installed: 1.24.4]
│   │   ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│   │   │   └── six [required: >=1.5, installed: 1.16.0]
│   │   ├── pytz [required: >=2020.1, installed: 2024.1]
│   │   └── tzdata [required: >=2022.7, installed: 2024.1]
│   ├── toolz [required: Any, installed: 0.12.1]
│   └── typing_extensions [required: >=4.0.1, installed: 4.9.0]
├── fastapi [required: Any, installed: 0.111.0]
│   ├── email_validator [required: >=2.0.0, installed: 2.1.2]
│   │   ├── dnspython [required: >=2.0.0, installed: 2.6.1]
│   │   └── idna [required: >=2.0.0, installed: 3.3]
│   ├── fastapi-cli [required: >=0.0.2, installed: 0.0.4]
│   │   └── typer [required: >=0.12.3, installed: 0.12.3]
│   │       ├── click [required: >=8.0.0, installed: 8.1.7]
│   │       │   └── colorama [required: Any, installed: 0.4.6]
│   │       ├── rich [required: >=10.11.0, installed: 13.7.1]
│   │       │   ├── markdown-it-py [required: >=2.2.0, installed: 3.0.0]
│   │       │   │   └── mdurl [required: ~=0.1, installed: 0.1.2]
│   │       │   └── Pygments [required: >=2.13.0,<3.0.0, installed: 2.18.0]
│   │       ├── shellingham [required: >=1.3.0, installed: 1.5.4]
│   │       └── typing_extensions [required: >=3.7.4.3, installed: 4.9.0]
│   ├── httpx [required: >=0.23.0, installed: 0.24.1]
│   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   ├── httpcore [required: >=0.15.0,<0.18.0, installed: 0.17.3]
│   │   │   ├── anyio [required: >=3.0,<5.0, installed: 4.4.0]
│   │   │   │   ├── exceptiongroup [required: >=1.0.2, installed: 1.2.1]
│   │   │   │   ├── idna [required: >=2.8, installed: 3.3]
│   │   │   │   ├── sniffio [required: >=1.1, installed: 1.2.0]
│   │   │   │   └── typing_extensions [required: >=4.1, installed: 4.9.0]
│   │   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   │   ├── h11 [required: >=0.13,<0.15, installed: 0.13.0]
│   │   │   └── sniffio [required: ==1.*, installed: 1.2.0]
│   │   ├── idna [required: Any, installed: 3.3]
│   │   └── sniffio [required: Any, installed: 1.2.0]
│   ├── Jinja2 [required: >=2.11.2, installed: 3.1.3]
│   │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
│   ├── orjson [required: >=3.2.1, installed: 3.10.5]
│   ├── pydantic [required: >=1.7.4,<3.0.0,!=2.1.0,!=2.0.1,!=2.0.0,!=1.8.1,!=1.8, installed: 2.7.4]
│   │   ├── annotated-types [required: >=0.4.0, installed: 0.7.0]
│   │   ├── pydantic_core [required: ==2.18.4, installed: 2.18.4]
│   │   │   └── typing_extensions [required: >=4.6.0,!=4.7.0, installed: 4.9.0]
│   │   └── typing_extensions [required: >=4.6.1, installed: 4.9.0]
│   ├── python-multipart [required: >=0.0.7, installed: 0.0.9]
│   ├── starlette [required: >=0.37.2,<0.38.0, installed: 0.37.2]
│   │   └── anyio [required: >=3.4.0,<5, installed: 4.4.0]
│   │       ├── exceptiongroup [required: >=1.0.2, installed: 1.2.1]
│   │       ├── idna [required: >=2.8, installed: 3.3]
│   │       ├── sniffio [required: >=1.1, installed: 1.2.0]
│   │       └── typing_extensions [required: >=4.1, installed: 4.9.0]
│   ├── typing_extensions [required: >=4.8.0, installed: 4.9.0]
│   ├── ujson [required: >=4.0.1,!=5.1.0,!=5.0.0,!=4.3.0,!=4.2.0,!=4.1.0,!=4.0.2, installed: 5.10.0]
│   └── uvicorn [required: >=0.12.0, installed: 0.30.1]
│       ├── click [required: >=7.0, installed: 8.1.7]
│       │   └── colorama [required: Any, installed: 0.4.6]
│       ├── h11 [required: >=0.8, installed: 0.13.0]
│       └── typing_extensions [required: >=4.0, installed: 4.9.0]
├── ffmpy [required: Any, installed: 0.3.2]
├── gradio_client [required: ==1.0.1, installed: 1.0.1]
│   ├── fsspec [required: Any, installed: 2024.2.0]
│   ├── httpx [required: >=0.24.1, installed: 0.24.1]
│   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   ├── httpcore [required: >=0.15.0,<0.18.0, installed: 0.17.3]
│   │   │   ├── anyio [required: >=3.0,<5.0, installed: 4.4.0]
│   │   │   │   ├── exceptiongroup [required: >=1.0.2, installed: 1.2.1]
│   │   │   │   ├── idna [required: >=2.8, installed: 3.3]
│   │   │   │   ├── sniffio [required: >=1.1, installed: 1.2.0]
│   │   │   │   └── typing_extensions [required: >=4.1, installed: 4.9.0]
│   │   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   │   ├── h11 [required: >=0.13,<0.15, installed: 0.13.0]
│   │   │   └── sniffio [required: ==1.*, installed: 1.2.0]
│   │   ├── idna [required: Any, installed: 3.3]
│   │   └── sniffio [required: Any, installed: 1.2.0]
│   ├── huggingface-hub [required: >=0.19.3, installed: 0.23.4]
│   │   ├── filelock [required: Any, installed: 3.13.1]
│   │   ├── fsspec [required: >=2023.5.0, installed: 2024.2.0]
│   │   ├── packaging [required: >=20.9, installed: 24.0]
│   │   ├── PyYAML [required: >=5.1, installed: 6.0.1]
│   │   ├── requests [required: Any, installed: 2.32.3]
│   │   │   ├── certifi [required: >=2017.4.17, installed: 2022.6.15]
│   │   │   ├── charset-normalizer [required: >=2,<4, installed: 2.1.0]
│   │   │   ├── idna [required: >=2.5,<4, installed: 3.3]
│   │   │   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.2]
│   │   ├── tqdm [required: >=4.42.1, installed: 4.66.4]
│   │   │   └── colorama [required: Any, installed: 0.4.6]
│   │   └── typing_extensions [required: >=3.7.4.3, installed: 4.9.0]
│   ├── packaging [required: Any, installed: 24.0]
│   ├── typing_extensions [required: ~=4.0, installed: 4.9.0]
│   └── websockets [required: >=10.0,<12.0, installed: 11.0.3]
├── httpx [required: >=0.24.1, installed: 0.24.1]
│   ├── certifi [required: Any, installed: 2022.6.15]
│   ├── httpcore [required: >=0.15.0,<0.18.0, installed: 0.17.3]
│   │   ├── anyio [required: >=3.0,<5.0, installed: 4.4.0]
│   │   │   ├── exceptiongroup [required: >=1.0.2, installed: 1.2.1]
│   │   │   ├── idna [required: >=2.8, installed: 3.3]
│   │   │   ├── sniffio [required: >=1.1, installed: 1.2.0]
│   │   │   └── typing_extensions [required: >=4.1, installed: 4.9.0]
│   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   ├── h11 [required: >=0.13,<0.15, installed: 0.13.0]
│   │   └── sniffio [required: ==1.*, installed: 1.2.0]
│   ├── idna [required: Any, installed: 3.3]
│   └── sniffio [required: Any, installed: 1.2.0]
├── huggingface-hub [required: >=0.19.3, installed: 0.23.4]
│   ├── filelock [required: Any, installed: 3.13.1]
│   ├── fsspec [required: >=2023.5.0, installed: 2024.2.0]
│   ├── packaging [required: >=20.9, installed: 24.0]
│   ├── PyYAML [required: >=5.1, installed: 6.0.1]
│   ├── requests [required: Any, installed: 2.32.3]
│   │   ├── certifi [required: >=2017.4.17, installed: 2022.6.15]
│   │   ├── charset-normalizer [required: >=2,<4, installed: 2.1.0]
│   │   ├── idna [required: >=2.5,<4, installed: 3.3]
│   │   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.2]
│   ├── tqdm [required: >=4.42.1, installed: 4.66.4]
│   │   └── colorama [required: Any, installed: 0.4.6]
│   └── typing_extensions [required: >=3.7.4.3, installed: 4.9.0]
├── importlib_resources [required: >=1.3,<7.0, installed: 6.4.0]
├── Jinja2 [required: <4.0, installed: 3.1.3]
│   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
├── MarkupSafe [required: ~=2.0, installed: 2.1.5]
├── matplotlib [required: ~=3.0, installed: 3.8.4]
│   ├── contourpy [required: >=1.0.1, installed: 1.2.1]
│   │   └── numpy [required: >=1.20, installed: 1.24.4]
│   ├── cycler [required: >=0.10, installed: 0.12.1]
│   ├── fonttools [required: >=4.22.0, installed: 4.51.0]
│   ├── kiwisolver [required: >=1.3.1, installed: 1.4.5]
│   ├── numpy [required: >=1.21, installed: 1.24.4]
│   ├── packaging [required: >=20.0, installed: 24.0]
│   ├── pillow [required: >=8, installed: 10.2.0]
│   ├── pyparsing [required: >=2.3.1, installed: 3.1.2]
│   └── python-dateutil [required: >=2.7, installed: 2.9.0.post0]
│       └── six [required: >=1.5, installed: 1.16.0]
├── numpy [required: >=1.0,<3.0, installed: 1.24.4]
├── orjson [required: ~=3.0, installed: 3.10.5]
├── packaging [required: Any, installed: 24.0]
├── pandas [required: >=1.0,<3.0, installed: 2.2.2]
│   ├── numpy [required: >=1.22.4, installed: 1.24.4]
│   ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   ├── pytz [required: >=2020.1, installed: 2024.1]
│   └── tzdata [required: >=2022.7, installed: 2024.1]
├── pillow [required: >=8.0,<11.0, installed: 10.2.0]
├── pydantic [required: >=2.0, installed: 2.7.4]
│   ├── annotated-types [required: >=0.4.0, installed: 0.7.0]
│   ├── pydantic_core [required: ==2.18.4, installed: 2.18.4]
│   │   └── typing_extensions [required: >=4.6.0,!=4.7.0, installed: 4.9.0]
│   └── typing_extensions [required: >=4.6.1, installed: 4.9.0]
├── pydub [required: Any, installed: 0.25.1]
├── python-multipart [required: >=0.0.9, installed: 0.0.9]
├── PyYAML [required: >=5.0,<7.0, installed: 6.0.1]
├── ruff [required: >=0.2.2, installed: 0.4.9]
├── semantic-version [required: ~=2.0, installed: 2.10.0]
├── tomlkit [required: ==0.12.0, installed: 0.12.0]
├── typer [required: >=0.12,<1.0, installed: 0.12.3]
│   ├── click [required: >=8.0.0, installed: 8.1.7]
│   │   └── colorama [required: Any, installed: 0.4.6]
│   ├── rich [required: >=10.11.0, installed: 13.7.1]
│   │   ├── markdown-it-py [required: >=2.2.0, installed: 3.0.0]
│   │   │   └── mdurl [required: ~=0.1, installed: 0.1.2]
│   │   └── Pygments [required: >=2.13.0,<3.0.0, installed: 2.18.0]
│   ├── shellingham [required: >=1.3.0, installed: 1.5.4]
│   └── typing_extensions [required: >=3.7.4.3, installed: 4.9.0]
├── typing_extensions [required: ~=4.0, installed: 4.9.0]
├── urllib3 [required: ~=2.0, installed: 2.2.2]
└── uvicorn [required: >=0.14.0, installed: 0.30.1]
    ├── click [required: >=7.0, installed: 8.1.7]
    │   └── colorama [required: Any, installed: 0.4.6]
    ├── h11 [required: >=0.8, installed: 0.13.0]
    └── typing_extensions [required: >=4.0, installed: 4.9.0]
httptools==0.6.1
ipykernel==6.29.4
├── comm [required: >=0.1.1, installed: 0.2.2]
│   └── traitlets [required: >=4, installed: 5.14.3]
├── debugpy [required: >=1.6.5, installed: 1.8.1]
├── ipython [required: >=7.23.1, installed: 8.24.0]
│   ├── colorama [required: Any, installed: 0.4.6]
│   ├── decorator [required: Any, installed: 5.1.1]
│   ├── exceptiongroup [required: Any, installed: 1.2.1]
│   ├── jedi [required: >=0.16, installed: 0.19.1]
│   │   └── parso [required: >=0.8.3,<0.9.0, installed: 0.8.4]
│   ├── matplotlib-inline [required: Any, installed: 0.1.7]
│   │   └── traitlets [required: Any, installed: 5.14.3]
│   ├── prompt-toolkit [required: >=3.0.41,<3.1.0, installed: 3.0.43]
│   │   └── wcwidth [required: Any, installed: 0.2.13]
│   ├── Pygments [required: >=2.4.0, installed: 2.18.0]
│   ├── stack-data [required: Any, installed: 0.6.3]
│   │   ├── asttokens [required: >=2.1.0, installed: 2.4.1]
│   │   │   └── six [required: >=1.12.0, installed: 1.16.0]
│   │   ├── executing [required: >=1.2.0, installed: 2.0.1]
│   │   └── pure-eval [required: Any, installed: 0.2.2]
│   ├── traitlets [required: >=5.13.0, installed: 5.14.3]
│   └── typing_extensions [required: >=4.6, installed: 4.9.0]
├── jupyter_client [required: >=6.1.12, installed: 8.6.1]
│   ├── jupyter_core [required: >=4.12,!=5.0.*, installed: 5.7.2]
│   │   ├── platformdirs [required: >=2.5, installed: 4.2.1]
│   │   ├── pywin32 [required: >=300, installed: 306]
│   │   └── traitlets [required: >=5.3, installed: 5.14.3]
│   ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   ├── pyzmq [required: >=23.0, installed: 26.0.3]
│   ├── tornado [required: >=6.2, installed: 6.4]
│   └── traitlets [required: >=5.3, installed: 5.14.3]
├── jupyter_core [required: >=4.12,!=5.0.*, installed: 5.7.2]
│   ├── platformdirs [required: >=2.5, installed: 4.2.1]
│   ├── pywin32 [required: >=300, installed: 306]
│   └── traitlets [required: >=5.3, installed: 5.14.3]
├── matplotlib-inline [required: >=0.1, installed: 0.1.7]
│   └── traitlets [required: Any, installed: 5.14.3]
├── nest-asyncio [required: Any, installed: 1.6.0]
├── packaging [required: Any, installed: 24.0]
├── psutil [required: Any, installed: 5.9.8]
├── pyzmq [required: >=24, installed: 26.0.3]
├── tornado [required: >=6.1, installed: 6.4]
└── traitlets [required: >=5.4.0, installed: 5.14.3]
markdown2==2.4.13
mlxtend==0.23.1
├── joblib [required: >=0.13.2, installed: 1.4.2]
├── matplotlib [required: >=3.0.0, installed: 3.8.4]
│   ├── contourpy [required: >=1.0.1, installed: 1.2.1]
│   │   └── numpy [required: >=1.20, installed: 1.24.4]
│   ├── cycler [required: >=0.10, installed: 0.12.1]
│   ├── fonttools [required: >=4.22.0, installed: 4.51.0]
│   ├── kiwisolver [required: >=1.3.1, installed: 1.4.5]
│   ├── numpy [required: >=1.21, installed: 1.24.4]
│   ├── packaging [required: >=20.0, installed: 24.0]
│   ├── pillow [required: >=8, installed: 10.2.0]
│   ├── pyparsing [required: >=2.3.1, installed: 3.1.2]
│   └── python-dateutil [required: >=2.7, installed: 2.9.0.post0]
│       └── six [required: >=1.5, installed: 1.16.0]
├── numpy [required: >=1.16.2, installed: 1.24.4]
├── pandas [required: >=0.24.2, installed: 2.2.2]
│   ├── numpy [required: >=1.22.4, installed: 1.24.4]
│   ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   ├── pytz [required: >=2020.1, installed: 2024.1]
│   └── tzdata [required: >=2022.7, installed: 2024.1]
├── scikit-learn [required: >=1.0.2, installed: 1.4.2]
│   ├── joblib [required: >=1.2.0, installed: 1.4.2]
│   ├── numpy [required: >=1.19.5, installed: 1.24.4]
│   ├── scipy [required: >=1.6.0, installed: 1.13.0]
│   │   └── numpy [required: >=1.22.4,<2.3, installed: 1.24.4]
│   └── threadpoolctl [required: >=2.0.0, installed: 3.5.0]
└── scipy [required: >=1.2.1, installed: 1.13.0]
    └── numpy [required: >=1.22.4,<2.3, installed: 1.24.4]
openpyxl==3.0.10
└── et-xmlfile [required: Any, installed: 1.1.0]
paramiko==3.4.0
├── bcrypt [required: >=3.2, installed: 4.1.3]
├── cryptography [required: >=3.3, installed: 37.0.4]
│   └── cffi [required: >=1.12, installed: 1.15.1]
│       └── pycparser [required: Any, installed: 2.21]
└── PyNaCl [required: >=1.5, installed: 1.5.0]
    └── cffi [required: >=1.4.1, installed: 1.15.1]
        └── pycparser [required: Any, installed: 2.21]
pipdeptree==2.23.0
├── packaging [required: >=23.1, installed: 24.0]
└── pip [required: >=23.1.2, installed: 24.1]
pycryptodome==3.20.0
pygame==2.1.2
pyOpenSSL==22.0.0
└── cryptography [required: >=35.0, installed: 37.0.4]
    └── cffi [required: >=1.12, installed: 1.15.1]
        └── pycparser [required: Any, installed: 2.21]
PySocks==1.7.1
python-dotenv==1.0.1
selenium==4.3.0
├── trio [required: ~=0.17, installed: 0.21.0]
│   ├── async-generator [required: >=1.9, installed: 1.10]
│   ├── attrs [required: >=19.2.0, installed: 23.2.0]
│   ├── cffi [required: >=1.14, installed: 1.15.1]
│   │   └── pycparser [required: Any, installed: 2.21]
│   ├── idna [required: Any, installed: 3.3]
│   ├── outcome [required: Any, installed: 1.2.0]
│   │   └── attrs [required: >=19.2.0, installed: 23.2.0]
│   ├── sniffio [required: Any, installed: 1.2.0]
│   └── sortedcontainers [required: Any, installed: 2.4.0]
├── trio-websocket [required: ~=0.9, installed: 0.9.2]
│   ├── async-generator [required: >=1.10, installed: 1.10]
│   ├── trio [required: >=0.11, installed: 0.21.0]
│   │   ├── async-generator [required: >=1.9, installed: 1.10]
│   │   ├── attrs [required: >=19.2.0, installed: 23.2.0]
│   │   ├── cffi [required: >=1.14, installed: 1.15.1]
│   │   │   └── pycparser [required: Any, installed: 2.21]
│   │   ├── idna [required: Any, installed: 3.3]
│   │   ├── outcome [required: Any, installed: 1.2.0]
│   │   │   └── attrs [required: >=19.2.0, installed: 23.2.0]
│   │   ├── sniffio [required: Any, installed: 1.2.0]
│   │   └── sortedcontainers [required: Any, installed: 2.4.0]
│   └── wsproto [required: >=0.14, installed: 1.1.0]
│       └── h11 [required: >=0.9.0,<1, installed: 0.13.0]
└── urllib3 [required: ~=1.26, installed: 2.2.2]
torch-tb-profiler==0.4.3
├── pandas [required: >=1.0.0, installed: 2.2.2]
│   ├── numpy [required: >=1.22.4, installed: 1.24.4]
│   ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   ├── pytz [required: >=2020.1, installed: 2024.1]
│   └── tzdata [required: >=2022.7, installed: 2024.1]
└── tensorboard [required: >=1.15,!=2.1.0, installed: 2.17.0]
    ├── absl-py [required: >=0.4, installed: 2.1.0]
    ├── grpcio [required: >=1.48.2, installed: 1.64.1]
    ├── Markdown [required: >=2.6.8, installed: 3.6]
    ├── numpy [required: >=1.12.0, installed: 1.24.4]
    ├── protobuf [required: >=3.19.6,<5.0.0,!=4.24.0, installed: 4.25.3]
    ├── setuptools [required: >=41.0.0, installed: 58.1.0]
    ├── six [required: >1.9, installed: 1.16.0]
    ├── tensorboard-data-server [required: >=0.7.0,<0.8.0, installed: 0.7.2]
    └── Werkzeug [required: >=1.0.1, installed: 3.0.3]
        └── MarkupSafe [required: >=2.1.1, installed: 2.1.5]
torchaudio==2.3.1
└── torch [required: ==2.3.1, installed: 2.3.1]
    ├── filelock [required: Any, installed: 3.13.1]
    ├── fsspec [required: Any, installed: 2024.2.0]
    ├── Jinja2 [required: Any, installed: 3.1.3]
    │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
    ├── mkl [required: >=2021.1.1,<=2021.4.0, installed: 2021.4.0]
    │   ├── intel-openmp [required: ==2021.*, installed: 2021.4.0]
    │   └── tbb [required: ==2021.*, installed: 2021.11.0]
    ├── networkx [required: Any, installed: 3.2.1]
    ├── sympy [required: Any, installed: 1.12]
    │   └── mpmath [required: >=0.19, installed: 1.3.0]
    └── typing_extensions [required: >=4.8.0, installed: 4.9.0]
torchinfo==1.8.0
torchmetrics==1.4.0.post0
├── lightning-utilities [required: >=0.8.0, installed: 0.11.2]
│   ├── packaging [required: >=17.1, installed: 24.0]
│   ├── setuptools [required: Any, installed: 58.1.0]
│   └── typing_extensions [required: Any, installed: 4.9.0]
├── numpy [required: >1.20.0, installed: 1.24.4]
├── packaging [required: >17.1, installed: 24.0]
└── torch [required: >=1.10.0, installed: 2.3.1]
    ├── filelock [required: Any, installed: 3.13.1]
    ├── fsspec [required: Any, installed: 2024.2.0]
    ├── Jinja2 [required: Any, installed: 3.1.3]
    │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
    ├── mkl [required: >=2021.1.1,<=2021.4.0, installed: 2021.4.0]
    │   ├── intel-openmp [required: ==2021.*, installed: 2021.4.0]
    │   └── tbb [required: ==2021.*, installed: 2021.11.0]
    ├── networkx [required: Any, installed: 3.2.1]
    ├── sympy [required: Any, installed: 1.12]
    │   └── mpmath [required: >=0.19, installed: 1.3.0]
    └── typing_extensions [required: >=4.8.0, installed: 4.9.0]
torchvision==0.18.1
├── numpy [required: Any, installed: 1.24.4]
├── pillow [required: >=5.3.0,!=8.3.*, installed: 10.2.0]
└── torch [required: ==2.3.1, installed: 2.3.1]
    ├── filelock [required: Any, installed: 3.13.1]
    ├── fsspec [required: Any, installed: 2024.2.0]
    ├── Jinja2 [required: Any, installed: 3.1.3]
    │   └── MarkupSafe [required: >=2.0, installed: 2.1.5]
    ├── mkl [required: >=2021.1.1,<=2021.4.0, installed: 2021.4.0]
    │   ├── intel-openmp [required: ==2021.*, installed: 2021.4.0]
    │   └── tbb [required: ==2021.*, installed: 2021.11.0]
    ├── networkx [required: Any, installed: 3.2.1]
    ├── sympy [required: Any, installed: 1.12]
    │   └── mpmath [required: >=0.19, installed: 1.3.0]
    └── typing_extensions [required: >=4.8.0, installed: 4.9.0]
watchfiles==0.22.0
└── anyio [required: >=3.0.0, installed: 4.4.0]
    ├── exceptiongroup [required: >=1.0.2, installed: 1.2.1]
    ├── idna [required: >=2.8, installed: 3.3]
    ├── sniffio [required: >=1.1, installed: 1.2.0]
    └── typing_extensions [required: >=4.1, installed: 4.9.0]

**Comment by pritesh2000** [comment]
I had the same error, Here issue is numpy 2.0.0 is not compatible with other dependencies. So you have to downgrade numpy to make it run

You can add
numpy==1.26.4
in the beginning of your requirements.txt file and it will run

**Comment by pritesh2000** [comment]
Does this work ??

**Comment by huangBnn** [comment]
i solve it already~ it's a compatibility problem on huggingface.
revise on the requirement.txt:
torch==2.3.0
torchversion==0.18.0
thank you~
