### ISSUE TITLE
Helper Function github link requests error

### ISSUE THREAD

**Issue by Syed-Tangim-Pasha** [mrdbourke/pytorch-deep-learning#995]
I tried to use the helper function through your GitHub link using the raw files URL, but it showed an error. Could you please help me with the problem related to the below issue and how I can resolve it?

Code:

import requests
from pathlib import Path 

url="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/helper_functions.py"

# Download helper functions from Learn PyTorch repo (if not already downloaded)
if Path("helper_functions.py").is_file():
  print("helper_functions.py already exists, skipping download")
else:
  print("Downloading helper_functions.py")
  request = requests.get(url)
  with open("helper_functions.py", "wb") as f:
    f.write(request.content)

from helper_functions import plot_predictions, plot_decision_boundary

Error Messages:

helper_functions.py already exists, skipping download
Traceback (most recent call last):

  File "/content/helper_functions.py", line 112
    <title>pytorch-deep-learning/helper_functions.py at main · mrdbourke/pytorch-deep-learning · GitHub</title>
                                                             ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by pritesh2000** [comment]
It is not link related error you might type somewhere '.' without knowing and that is causing it.

You can use *```* (button before 1 thrice) before and after code to make code snippet like this
```
print("Hello world")
```

**Comment by Syed-Tangim-Pasha** [comment]
> It is not link related error you might type somewhere '.' without knowing and that is causing it.
> 
> You can use _```_ (button before 1 thrice) before and after code to make code snippet like this
> 
> ```
> print("Hello world")
> ```
> 
> can you add screenshot here?
