### ISSUE TITLE
 How to Create GitHub Pages from Scratch?

### ISSUE THREAD

**Issue by nerbivol** [mrdbourke/pytorch-deep-learning#997]
Hello everyone,

I am new to GitHub Pages and I would like to create a GitHub Pages site from scratch. Could someone guide me through the process? Here are some specific points I need help with:

1. **Repository Setup**: How do I set up a repository for GitHub Pages?
2. **Branch Configuration**: Which branch should I use for my GitHub Pages site (main, gh-pages, or any other)?
3. **Custom Domain**: How can I use a custom domain for my GitHub Pages site for example `learnmath.io`?

Any detailed steps, resources, or examples would be greatly appreciated. Thanks in advance for your help!

**Comment by SaurinSavla** [comment]
Hi @nerbivol, GitHub pages are fairly easy to set up. 

1. To start with create a new github public repository with your username followed by ".github.io"
Eg: "__username__.github.io" should be the repository name ps Replace "__username__" with your github username.

2. You can use any branch of your repository. You can change that under Settings. 
https://docs.github.com/en/pages/quickstart

4. Visit - this url, they have given it in detail.
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
